// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiaZ60NFSZfyXeYSc_BwT01EDf7pYGzdo',
    appId: '1:107816987237:web:0ce710439e04b34db5348c',
    messagingSenderId: '107816987237',
    projectId: 'signup-c67cf',
    authDomain: 'signup-c67cf.firebaseapp.com',
    storageBucket: 'signup-c67cf.firebasestorage.app',
    measurementId: 'G-1837CFGQXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHFfYYU-ZNxazw4OcqluOAm_BeNz7KwOw',
    appId: '1:107816987237:android:3c5390ad945ab495b5348c',
    messagingSenderId: '107816987237',
    projectId: 'signup-c67cf',
    storageBucket: 'signup-c67cf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiaZ60NFSZfyXeYSc_BwT01EDf7pYGzdo',
    appId: '1:107816987237:web:b7623dac36deb084b5348c',
    messagingSenderId: '107816987237',
    projectId: 'signup-c67cf',
    authDomain: 'signup-c67cf.firebaseapp.com',
    storageBucket: 'signup-c67cf.firebasestorage.app',
    measurementId: 'G-60LDVBD51F',
  );
}
